# Site settings
author: Ellen Park
title: Exploration of Coding
header-img: img/home-bg.png
email: ellenupark@gmail.com
copyright_name: Ellen Park
description: > # this means to ignore newlines until "baseurl:"
  a personal journey through software engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ellenupark

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
